# Site settings
title: Lance's Blog
email:
description: "Resurrecting an old blog."
baseurl: ""
url: "http://rlancemartin.github.io"
twitter_username: rlancemartin
github_username: rlancemartin

# Build settings
markdown: redcarpet
permalink: pretty
